### ISSUE TITLE
Docker 10.2.1 Post Build Images Tests

### ISSUE THREAD

**Issue by colmose** [colmose/pb_test#52]
For each of the following Docker Images, do the following:
### Setup:
* `Docker pull` the relevant image
* `Docker run` the image - using the `Docker run` command found on the Dockerhub page  **for that image**

### Tests:
* Ensure connection is possible to Investigate port (`5606`) in a browser
* For images other than `siren-investigate`
	* ensure connection is possible to Elasticsearch (`9220`)

- [ ] `siren-platform-demo-data`
- [ ] `siren-platform`
- [ ] `siren-investigate`

#### To test Siren Investigate image
* Ensure you have read privileges for the siren-investigate and siren-platform-no-data-no-security repositories on dockerhub
* Make sure docker-compose is installed
* create a new file called `docker-compose.yml` containing:
```
version: '3'
services:
  investigate:
    image: sirensolutions/siren-investigate:XXX
    ports:
      - "5606:5606"
    container_name: investigate
    environment:
      sirenlogs: host
      ELASTICSEARCH_URL: http://nodatanosec:9220
  nodatanosec:
    image: sirensolutions/siren-platform-no-data-no-security:XXX
    expose:
      - "9220"
    container_name: nodatanosec
```
* Run `docker-compose up`
